export const WITH_DOT_ALIAS_TEST_DATA = [
  [
    {
      testName: 'GroupBySQLInnerQuery',
      expectedSQL: `SELECT SUM(order_amount) AS "orders.total_order_amount" ,   "orders.order_month" FROM (SELECT DATE_TRUNC('month', order_date) AS "orders.order_month", * FROM (select * from orders) AS orders) AS orders GROUP BY "orders.order_month" LIMIT 1`,
      cubeInput: {
        measures: ['orders.total_order_amount'],
        filters: [],
        dimensions: ['orders.order_month'],
        limit: 1,
      },
      expectedOutput: [
        {
          'orders.order_month': '2022-01-01T00:00:00.000Z',
          'orders.total_order_amount': 130,
        },
      ],
    },
  ],
  [
    {
      testName: 'GroupBy',
      expectedSQL: `SELECT SUM(order_amount) AS "orders.total_order_amount" ,   "orders.customer_id" FROM (SELECT customer_id AS "orders.customer_id", * FROM (select * from orders) AS orders) AS orders GROUP BY "orders.customer_id" ORDER BY "orders.total_order_amount" ASC, "orders.customer_id" ASC`,
      cubeInput: {
        measures: ['orders.total_order_amount'],
        filters: [],
        dimensions: ['orders.customer_id'],
        order: {
          'orders.total_order_amount': 'asc',
          'orders.customer_id': 'asc',
        },
      },
      expectedOutput: [
        {
          'orders.customer_id': '6aa6',
          'orders.total_order_amount': 0,
        },
        {
          'orders.customer_id': '2',
          'orders.total_order_amount': 100,
        },
        {
          'orders.customer_id': '3',
          'orders.total_order_amount': 100,
        },
        {
          'orders.customer_id': '7',
          'orders.total_order_amount': 100,
        },
        {
          'orders.customer_id': null,
          'orders.total_order_amount': 100,
        },
        {
          'orders.customer_id': '6',
          'orders.total_order_amount': 120,
        },
        {
          'orders.customer_id': '1',
          'orders.total_order_amount': 130,
        },
        {
          'orders.customer_id': '4',
          'orders.total_order_amount': 135,
        },
        {
          'orders.customer_id': '5',
          'orders.total_order_amount': 150,
        },
      ],
    },
  ],
  [
    {
      testName: 'Equals',
      expectedSQL: `SELECT orders.* FROM (SELECT customer_id AS "orders.customer_id", * FROM (select * from orders) AS orders) AS orders WHERE ("orders.customer_id" = '1')`,
      cubeInput: {
        measures: ['*'],
        filters: [
          {
            member: 'orders.customer_id',
            operator: 'equals',
            values: ['1'],
          },
        ],
        dimensions: [],
      },
      expectedOutput: [
        {
          order_id: 1,
          customer_id: '1',
          'orders.customer_id': '1',
          product_id: '1',
          order_date: '2022-01-01',
          order_amount: 50.0,
          vendors: ['myntra', 'amazon', 'flipkart'],
        },
        {
          order_id: 2,
          customer_id: '1',
          'orders.customer_id': '1',
          product_id: '2',
          order_date: '2022-01-02',
          order_amount: 80.0,
          vendors: ['myntra'],
        },
      ],
    },
    {
      testName: 'Equals for multiple values',
      expectedSQL: `SELECT orders.* FROM (SELECT customer_id AS "orders.customer_id", * FROM (select * from orders) AS orders) AS orders WHERE (("orders.customer_id" = '1') AND ("orders.customer_id" = '2'))`,
      cubeInput: {
        measures: ['*'],
        filters: [
          {
            member: 'orders.customer_id',
            operator: 'equals',
            values: ['1', '2'],
          },
        ],
        dimensions: [],
      },
      expectedOutput: [],
    },
  ],
  [
    {
      testName: 'NotEquals',
      expectedSQL: `SELECT orders.* FROM (SELECT customer_id AS "orders.customer_id", * FROM (select * from orders) AS orders) AS orders WHERE ("orders.customer_id" != '1')`,
      cubeInput: {
        measures: ['*'],
        filters: [
          {
            member: 'orders.customer_id',
            operator: 'notEquals',
            values: ['1'],
          },
        ],
        dimensions: [],
      },
      expectedOutput: [
        {
          order_id: 3,
          customer_id: '2',
          'orders.customer_id': '2',
          product_id: '3',
          order_date: '2022-02-01',
          order_amount: 25.0,
          vendors: [],
        },
        {
          order_id: 4,
          customer_id: '2',
          'orders.customer_id': '2',
          product_id: '1',
          order_date: '2022-03-01',
          order_amount: 75.0,
          vendors: ['flipkart'],
        },
        {
          order_id: 5,
          customer_id: '3',
          'orders.customer_id': '3',
          product_id: '1',
          order_date: '2022-03-02',
          order_amount: 100.0,
          vendors: ['myntra', 'amazon', 'flipkart'],
        },
        {
          order_id: 6,
          customer_id: '4',
          'orders.customer_id': '4',
          product_id: '2',
          order_date: '2022-04-01',
          order_amount: 45.0,
          vendors: [],
        },
        {
          order_id: 7,
          customer_id: '4',
          'orders.customer_id': '4',
          product_id: '3',
          order_date: '2022-05-01',
          order_amount: 90.0,
          vendors: ['myntra', 'flipkart'],
        },
        {
          order_id: 8,
          customer_id: '5',
          'orders.customer_id': '5',
          product_id: '1',
          order_date: '2022-05-02',
          order_amount: 65.0,
          vendors: ['amazon', 'flipkart'],
        },
        {
          order_id: 9,
          customer_id: '5',
          'orders.customer_id': '5',
          product_id: '2',
          order_date: '2022-05-05',
          order_amount: 85.0,
          vendors: [],
        },
        {
          order_id: 10,
          customer_id: '6',
          'orders.customer_id': '6',
          product_id: '3',
          order_date: '2022-06-01',
          order_amount: 120.0,
          vendors: ['myntra', 'amazon'],
        },
        {
          order_id: 11,
          customer_id: '6aa6',
          'orders.customer_id': '6aa6',
          product_id: '3',
          order_date: '2024-06-01',
          order_amount: 0.0,
          vendors: ['amazon'],
        },
        {
          order_id: 13,
          customer_id: '7',
          'orders.customer_id': '7',
          product_id: '6',
          order_date: '2024-08-01',
          order_amount: 100.0,
          vendors: ["swiggy's"],
        },
      ],
    },
  ],
  [
    {
      testName: 'Contains',
      expectedSQL: `SELECT orders.* FROM (SELECT customer_id AS "orders.customer_id", * FROM (select * from orders) AS orders) AS orders WHERE ("orders.customer_id" ~~* '%aa%')`,
      cubeInput: {
        measures: ['*'],
        filters: [
          {
            member: 'orders.customer_id',
            operator: 'contains',
            values: ['aa'],
          },
        ],
        dimensions: [],
      },
      expectedOutput: [
        {
          order_id: 11,
          customer_id: '6aa6',
          'orders.customer_id': '6aa6',
          product_id: '3',
          order_date: '2024-06-01',
          order_amount: 0.0,
          vendors: ['amazon'],
        },
      ],
    },
  ],
  [
    {
      testName: 'NotContains',
      expectedSQL: `SELECT orders.* FROM (SELECT customer_id AS "orders.customer_id", * FROM (select * from orders) AS orders) AS orders WHERE (("orders.customer_id" !~~ '%1%') AND ("orders.customer_id" !~~ '%2%') AND ("orders.customer_id" !~~ '%3%') AND ("orders.customer_id" !~~ '%4%') AND ("orders.customer_id" !~~ '%5%') AND ("orders.customer_id" !~~ '%aa%'))`,
      cubeInput: {
        measures: ['*'],
        filters: [
          {
            and: [
              {
                member: 'orders.customer_id',
                operator: 'notContains',
                values: ['1'],
              },
              {
                member: 'orders.customer_id',
                operator: 'notContains',
                values: ['2'],
              },
              {
                member: 'orders.customer_id',
                operator: 'notContains',
                values: ['3'],
              },
              {
                member: 'orders.customer_id',
                operator: 'notContains',
                values: ['4'],
              },
              {
                member: 'orders.customer_id',
                operator: 'notContains',
                values: ['5'],
              },
              {
                member: 'orders.customer_id',
                operator: 'notContains',
                values: ['aa'],
              },
            ],
          },
        ],
        dimensions: [],
      },
      expectedOutput: [
        {
          order_id: 10,
          customer_id: '6',
          'orders.customer_id': '6',
          product_id: '3',
          order_date: '2022-06-01',
          order_amount: 120,
          vendors: ['myntra', 'amazon'],
        },
        {
          customer_id: '7',
          order_amount: 100,
          order_date: '2024-08-01T00:00:00.000Z',
          order_id: 13,
          'orders.customer_id': '7',
          'orders.order_date': undefined,
          product_id: '6',
          vendors: ["swiggy's"],
        },
      ],
    },
  ],
  [
    {
      testName: 'GreaterThan',
      expectedSQL: `SELECT orders.* FROM (SELECT orders.order_amount AS "orders.order_amount", * FROM (select * from orders) AS orders) AS orders WHERE ("orders.order_amount" > 50)`,
      cubeInput: {
        measures: ['*'],
        filters: [
          {
            member: 'orders.order_amount',
            operator: 'gt',
            values: ['50'],
          },
        ],
        dimensions: [],
      },
      expectedOutput: [
        {
          order_id: 2,
          customer_id: '1',
          product_id: '2',
          order_date: '2022-01-02',
          order_amount: 80.0,
          'orders.order_amount': 80.0,
          vendors: ['myntra'],
        },
        {
          order_id: 4,
          customer_id: '2',
          product_id: '1',
          order_date: '2022-03-01',
          order_amount: 75.0,
          'orders.order_amount': 75.0,
          vendors: ['flipkart'],
        },
        {
          order_id: 5,
          customer_id: '3',
          product_id: '1',
          order_date: '2022-03-02',
          order_amount: 100.0,
          'orders.order_amount': 100.0,
          vendors: ['myntra', 'amazon', 'flipkart'],
        },
        {
          order_id: 7,
          customer_id: '4',
          product_id: '3',
          order_date: '2022-05-01',
          order_amount: 90.0,
          'orders.order_amount': 90.0,
          vendors: ['myntra', 'flipkart'],
        },
        {
          order_id: 8,
          customer_id: '5',
          product_id: '1',
          order_date: '2022-05-02',
          order_amount: 65.0,
          'orders.order_amount': 65.0,
          vendors: ['amazon', 'flipkart'],
        },
        {
          order_id: 9,
          customer_id: '5',
          product_id: '2',
          order_date: '2022-05-05',
          order_amount: 85.0,
          'orders.order_amount': 85.0,
          vendors: [],
        },
        {
          order_id: 10,
          customer_id: '6',
          product_id: '3',
          order_date: '2022-06-01',
          order_amount: 120.0,
          'orders.order_amount': 120.0,
          vendors: ['myntra', 'amazon'],
        },
        {
          customer_id: null,
          order_amount: 100,
          order_date: '2024-07-01T00:00:00.000Z',
          order_id: 12,
          'orders.order_amount': 100,
          'orders.order_date': undefined,
          product_id: '3',
          vendors: ['flipkart'],
        },
        {
          customer_id: '7',
          order_amount: 100,
          order_date: '2024-08-01T00:00:00.000Z',
          order_id: 13,
          'orders.order_amount': 100,
          'orders.order_date': undefined,
          product_id: '6',
          vendors: ["swiggy's"],
        },
      ],
    },
  ],
  [
    {
      testName: 'LessThan',
      expectedSQL: `SELECT orders.* FROM (SELECT orders.order_amount AS "orders.order_amount", * FROM (select * from orders) AS orders) AS orders WHERE ("orders.order_amount" < 50)`,
      cubeInput: {
        measures: ['*'],
        filters: [
          {
            member: 'orders.order_amount',
            operator: 'lt',
            values: ['50'],
          },
        ],
        dimensions: [],
      },
      expectedOutput: [
        {
          order_id: 3,
          customer_id: '2',
          product_id: '3',
          order_date: '2022-02-01',
          order_amount: 25.0,
          'orders.order_amount': 25.0,
          vendors: [],
        },
        {
          order_id: 6,
          customer_id: '4',
          product_id: '2',
          order_date: '2022-04-01',
          order_amount: 45.0,
          'orders.order_amount': 45.0,
          vendors: [],
        },
        {
          order_id: 11,
          customer_id: '6aa6',
          product_id: '3',
          order_date: '2024-06-01',
          order_amount: 0.0,
          'orders.order_amount': 0.0,
          vendors: ['amazon'],
        },
      ],
    },
  ],
  [
    {
      testName: 'InDateRange',
      expectedSQL: `SELECT orders.* FROM (SELECT order_date AS "orders.order_date", * FROM (select * from orders) AS orders) AS orders WHERE (("orders.order_date" >= '2022-02-01') AND ("orders.order_date" <= '2022-03-31'))`,
      cubeInput: {
        measures: ['*'],
        filters: [
          {
            member: 'orders.order_date',
            operator: 'inDateRange',
            values: ['2022-02-01', '2022-03-31'],
          },
        ],
        dimensions: [],
      },
      expectedOutput: [
        {
          order_id: 3,
          customer_id: '2',
          product_id: '3',
          order_date: '2022-02-01',
          'orders.order_date': '2022-02-01',
          order_amount: 25.0,
          vendors: [],
        },
        {
          order_id: 4,
          customer_id: '2',
          product_id: '1',
          order_date: '2022-03-01',
          'orders.order_date': '2022-03-01',
          order_amount: 75.0,
          vendors: ['flipkart'],
        },
        {
          order_id: 5,
          customer_id: '3',
          product_id: '1',
          order_date: '2022-03-02',
          'orders.order_date': '2022-03-02',
          order_amount: 100.0,
          vendors: ['myntra', 'amazon', 'flipkart'],
        },
      ],
    },
  ],
  [
    {
      testName: 'NotInDateRange',
      expectedSQL: `SELECT orders.* FROM (SELECT order_date AS "orders.order_date", * FROM (select * from orders) AS orders) AS orders WHERE (("orders.order_date" < '2022-02-01') OR ("orders.order_date" > '2022-03-31'))`,
      cubeInput: {
        measures: ['*'],
        filters: [
          {
            member: 'orders.order_date',
            operator: 'notInDateRange',
            values: ['2022-02-01', '2022-03-31'],
          },
        ],
        dimensions: [],
      },
      expectedOutput: [
        {
          order_id: 1,
          customer_id: '1',
          product_id: '1',
          order_date: '2022-01-01',
          order_amount: 50.0,
          'orders.order_date': '2022-01-01',
          vendors: ['myntra', 'amazon', 'flipkart'],
        },
        {
          order_id: 2,
          customer_id: '1',
          product_id: '2',
          order_date: '2022-01-02',
          order_amount: 80.0,
          'orders.order_date': '2022-01-02',
          vendors: ['myntra'],
        },
        {
          order_id: 6,
          customer_id: '4',
          product_id: '2',
          order_date: '2022-04-01',
          'orders.order_date': '2022-04-01',
          order_amount: 45.0,
          vendors: [],
        },
        {
          order_id: 7,
          customer_id: '4',
          product_id: '3',
          order_date: '2022-05-01',
          'orders.order_date': '2022-05-01',
          order_amount: 90.0,
          vendors: ['myntra', 'flipkart'],
        },
        {
          order_id: 8,
          customer_id: '5',
          product_id: '1',
          order_date: '2022-05-02',
          'orders.order_date': '2022-05-02',
          order_amount: 65.0,
          vendors: ['amazon', 'flipkart'],
        },
        {
          order_id: 9,
          customer_id: '5',
          product_id: '2',
          order_date: '2022-05-05',
          'orders.order_date': '2022-05-05',
          order_amount: 85.0,
          vendors: [],
        },
        {
          order_id: 10,
          customer_id: '6',
          product_id: '3',
          order_date: '2022-06-01',
          'orders.order_date': '2022-06-01',
          order_amount: 120.0,
          vendors: ['myntra', 'amazon'],
        },
        {
          order_id: 11,
          customer_id: '6aa6',
          product_id: '3',
          order_date: '2024-06-01',
          'orders.order_date': '2024-06-01',
          order_amount: 0.0,
          vendors: ['amazon'],
        },
        {
          customer_id: null,
          order_amount: 100,
          order_date: '2024-07-01T00:00:00.000Z',
          order_id: 12,
          'orders.order_date': '2024-07-01T00:00:00.000Z',
          product_id: '3',
          vendors: ['flipkart'],
        },
        {
          customer_id: '7',
          order_amount: 100,
          order_date: '2024-08-01T00:00:00.000Z',
          order_id: 13,
          'orders.order_date': '2024-08-01T00:00:00.000Z',
          product_id: '6',
          vendors: ["swiggy's"],
        },
      ],
    },
  ],
  [
    {
      testName: 'And',
      expectedSQL: `SELECT orders.* FROM (SELECT orders.order_amount AS "orders.order_amount", order_date AS "orders.order_date", * FROM (select * from orders) AS orders) AS orders WHERE (("orders.order_amount" > 50) AND (("orders.order_date" >= '2022-02-01') AND ("orders.order_date" <= '2022-06-01')))`,
      cubeInput: {
        measures: ['*'],
        filters: [
          {
            and: [
              {
                member: 'orders.order_amount',
                operator: 'gt',
                values: ['50'],
              },
              {
                member: 'orders.order_date',
                operator: 'inDateRange',
                values: ['2022-02-01', '2022-06-01'],
              },
            ],
          },
        ],
        dimensions: [],
      },
      expectedOutput: [
        {
          order_id: 4,
          customer_id: '2',
          product_id: '1',
          order_date: '2022-03-01',
          order_amount: 75.0,
          'orders.order_amount': 75.0,
          'orders.order_date': '2022-03-01',
          vendors: ['flipkart'],
        },
        {
          order_id: 5,
          customer_id: '3',
          product_id: '1',
          order_date: '2022-03-02',
          'orders.order_date': '2022-03-02',
          order_amount: 100.0,
          'orders.order_amount': 100.0,
          vendors: ['myntra', 'amazon', 'flipkart'],
        },
        {
          order_id: 7,
          customer_id: '4',
          product_id: '3',
          order_date: '2022-05-01',
          'orders.order_date': '2022-05-01',
          order_amount: 90.0,
          'orders.order_amount': 90.0,
          vendors: ['myntra', 'flipkart'],
        },
        {
          order_id: 8,
          customer_id: '5',
          product_id: '1',
          order_date: '2022-05-02',
          'orders.order_date': '2022-05-02',
          order_amount: 65,
          'orders.order_amount': 65,
          vendors: ['amazon', 'flipkart'],
        },
        {
          order_id: 9,
          customer_id: '5',
          product_id: '2',
          order_date: '2022-05-05',
          'orders.order_date': '2022-05-05',
          order_amount: 85.0,
          'orders.order_amount': 85.0,
          vendors: [],
        },
        {
          order_id: 10,
          customer_id: '6',
          product_id: '3',
          order_date: '2022-06-01',
          'orders.order_date': '2022-06-01',
          order_amount: 120.0,
          'orders.order_amount': 120.0,
          vendors: ['myntra', 'amazon'],
        },
      ],
    },
  ],
  [
    {
      testName: 'Set',
      expectedSQL: `SELECT orders.* FROM (SELECT orders.order_amount AS "orders.order_amount", product_id AS "orders.product_id", * FROM (select * from orders) AS orders) AS orders WHERE (("orders.order_amount" IS NOT NULL) AND ("orders.product_id" = '3'))`,
      cubeInput: {
        measures: ['*'],
        filters: [
          {
            and: [
              {
                member: 'orders.order_amount',
                operator: 'set',
              },
              {
                member: 'orders.product_id',
                operator: 'equals',
                values: ['3'],
              },
            ],
          },
        ],
        dimensions: [],
      },
      expectedOutput: [
        {
          customer_id: '2',
          order_amount: 25,
          order_date: '2022-02-01T00:00:00.000Z',
          order_id: 3,
          'orders.order_amount': 25,
          'orders.order_date': undefined,
          'orders.product_id': '3',
          product_id: '3',
          vendors: [],
        },
        {
          customer_id: '4',
          order_amount: 90,
          order_date: '2022-05-01T00:00:00.000Z',
          order_id: 7,
          'orders.order_amount': 90,
          'orders.order_date': undefined,
          'orders.product_id': '3',
          product_id: '3',
          vendors: ['myntra', 'flipkart'],
        },
        {
          customer_id: '6',
          order_amount: 120,
          order_date: '2022-06-01T00:00:00.000Z',
          order_id: 10,
          'orders.order_amount': 120,
          'orders.order_date': undefined,
          'orders.product_id': '3',
          product_id: '3',
          vendors: ['myntra', 'amazon'],
        },
        {
          customer_id: '6aa6',
          order_amount: 0,
          order_date: '2024-06-01T00:00:00.000Z',
          order_id: 11,
          'orders.order_amount': 0,
          'orders.order_date': undefined,
          'orders.product_id': '3',
          product_id: '3',
          vendors: ['amazon'],
        },
        {
          customer_id: null,
          order_amount: 100,
          order_date: '2024-07-01T00:00:00.000Z',
          order_id: 12,
          'orders.order_amount': 100,
          'orders.order_date': undefined,
          'orders.product_id': '3',
          product_id: '3',
          vendors: ['flipkart'],
        },
      ],
    },
  ],
  [
    {
      testName: 'Not Set',
      expectedSQL: `SELECT orders.* FROM (SELECT customer_id AS "orders.customer_id", product_id AS "orders.product_id", * FROM (select * from orders) AS orders) AS orders WHERE (("orders.customer_id" IS NULL) AND ("orders.product_id" = '3'))`,
      cubeInput: {
        measures: ['*'],
        filters: [
          {
            and: [
              {
                member: 'orders.customer_id',
                operator: 'notSet',
              },
              {
                member: 'orders.product_id',
                operator: 'equals',
                values: ['3'],
              },
            ],
          },
        ],
        dimensions: [],
      },
      expectedOutput: [
        {
          'orders.customer_id': null,
          customer_id: null,
          order_amount: 100,
          order_date: '2024-07-01T00:00:00.000Z',
          order_id: 12,
          'orders.order_date': undefined,
          'orders.product_id': '3',
          product_id: '3',
          vendors: ['flipkart'],
        },
      ],
    },
  ],
  [
    {
      testName: 'In',
      expectedSQL: `SELECT orders.* FROM (SELECT customer_id AS "orders.customer_id", vendors AS "orders.vendors", * FROM (select * from orders) AS orders) AS orders WHERE (("orders.customer_id" IN ('1', '2')) AND ("orders.vendors" && (ARRAY['myntra', 'amazon'])))`,
      cubeInput: {
        measures: ['*'],
        filters: [
          {
            and: [
              {
                member: 'orders.customer_id',
                operator: 'in',
                values: ['1', '2'],
              },
              {
                member: 'orders.vendors',
                operator: 'in',
                values: ['myntra', 'amazon'],
              },
            ],
          },
        ],
        dimensions: [],
      },
      expectedOutput: [
        {
          customer_id: '1',
          order_amount: 50,
          order_date: '2022-01-01T00:00:00.000Z',
          order_id: 1,
          'orders.customer_id': '1',
          'orders.order_date': undefined,
          'orders.vendors': ['myntra', 'amazon', 'flipkart'],
          product_id: '1',
          vendors: ['myntra', 'amazon', 'flipkart'],
        },
        {
          customer_id: '1',
          order_amount: 80,
          order_date: '2022-01-02T00:00:00.000Z',
          order_id: 2,
          'orders.customer_id': '1',
          'orders.order_date': undefined,
          'orders.vendors': ['myntra'],
          product_id: '2',
          vendors: ['myntra'],
        },
      ],
    },
    {
      testName: 'In with single quotes',
      expectedSQL: `SELECT orders.* FROM (SELECT vendors AS "orders.vendors", * FROM (select * from orders) AS orders) AS orders WHERE (("orders.vendors" && (ARRAY['swiggy''s'])))`,
      cubeInput: {
        measures: ['*'],
        filters: [
          {
            and: [
              {
                member: 'orders.vendors',
                operator: 'in',
                values: ["swiggy's"],
              },
            ],
          },
        ],
        dimensions: [],
      },
      expectedOutput: [
        {
          customer_id: '7',
          order_amount: 100,
          order_date: '2024-08-01T00:00:00.000Z',
          order_id: 13,
          'orders.order_date': undefined,
          'orders.vendors': ["swiggy's"],
          product_id: '6',
          vendors: ["swiggy's"],
        },
      ],
    },
  ],
  [
    {
      testName: 'Not In',
      expectedSQL: `SELECT orders.* FROM (SELECT customer_id AS "orders.customer_id", vendors AS "orders.vendors", * FROM (select * from orders) AS orders) AS orders WHERE ((("orders.customer_id" NOT IN ('1', '2')) OR ("orders.customer_id" IS NULL)) AND ((NOT ("orders.vendors" && (ARRAY['myntra', 'flipkart']))) OR ("orders.vendors" IS NULL)))`,
      cubeInput: {
        measures: ['*'],
        filters: [
          {
            and: [
              {
                member: 'orders.customer_id',
                operator: 'notIn',
                values: ['1', '2'],
              },
              {
                member: 'orders.vendors',
                operator: 'notIn',
                values: ['myntra', 'flipkart'],
              },
            ],
          },
        ],
        dimensions: [],
      },
      expectedOutput: [
        {
          customer_id: '4',
          order_amount: 45,
          order_date: '2022-04-01T00:00:00.000Z',
          order_id: 6,
          'orders.customer_id': '4',
          'orders.order_date': undefined,
          'orders.vendors': [],
          product_id: '2',
          vendors: [],
        },
        {
          customer_id: '5',
          order_amount: 85,
          order_date: '2022-05-05T00:00:00.000Z',
          order_id: 9,
          'orders.customer_id': '5',
          'orders.order_date': undefined,
          'orders.vendors': [],
          product_id: '2',
          vendors: [],
        },
        {
          customer_id: '6aa6',
          order_amount: 0,
          order_date: '2024-06-01T00:00:00.000Z',
          order_id: 11,
          'orders.customer_id': '6aa6',
          'orders.order_date': undefined,
          'orders.vendors': ['amazon'],
          product_id: '3',
          vendors: ['amazon'],
        },
        {
          customer_id: '7',
          order_amount: 100,
          order_date: '2024-08-01T00:00:00.000Z',
          order_id: 13,
          'orders.customer_id': '7',
          'orders.order_date': undefined,
          'orders.vendors': ["swiggy's"],
          product_id: '6',
          vendors: ["swiggy's"],
        },
      ],
    },
    {
      testName: 'Not In includes nulls',
      expectedSQL: `SELECT orders.* FROM (SELECT customer_id AS "orders.customer_id", product_id AS "orders.product_id", * FROM (select * from orders) AS orders) AS orders WHERE ((("orders.customer_id" NOT IN ('1', '2')) OR ("orders.customer_id" IS NULL)) AND ("orders.product_id" = '3'))`,
      cubeInput: {
        measures: ['*'],
        filters: [
          {
            and: [
              {
                member: 'orders.customer_id',
                operator: 'notIn',
                values: ['1', '2'],
              },
              {
                member: 'orders.product_id',
                operator: 'equals',
                values: ['3'],
              },
            ],
          },
        ],
        dimensions: [],
      },
      expectedOutput: [
        {
          customer_id: '4',
          order_amount: 90,
          order_date: '2022-05-01T00:00:00.000Z',
          order_id: 7,
          'orders.customer_id': '4',
          'orders.order_date': undefined,
          'orders.product_id': '3',
          product_id: '3',
          vendors: ['myntra', 'flipkart'],
        },
        {
          customer_id: '6',
          order_amount: 120,
          order_date: '2022-06-01T00:00:00.000Z',
          order_id: 10,
          'orders.customer_id': '6',
          'orders.order_date': undefined,
          'orders.product_id': '3',
          product_id: '3',
          vendors: ['myntra', 'amazon'],
        },
        {
          customer_id: '6aa6',
          order_amount: 0,
          order_date: '2024-06-01T00:00:00.000Z',
          order_id: 11,
          'orders.customer_id': '6aa6',
          'orders.order_date': undefined,
          'orders.product_id': '3',
          product_id: '3',
          vendors: ['amazon'],
        },
        {
          customer_id: null,
          order_amount: 100,
          order_date: '2024-07-01T00:00:00.000Z',
          order_id: 12,
          'orders.customer_id': null,
          'orders.order_date': undefined,
          'orders.product_id': '3',
          product_id: '3',
          vendors: ['flipkart'],
        },
      ],
    },
    {
      testName: 'Not In for array type',
      expectedSQL: `SELECT orders.* FROM (SELECT vendors AS "orders.vendors", * FROM (select * from orders) AS orders) AS orders WHERE ((NOT ("orders.vendors" && (ARRAY['myntra', 'amazon']))) OR ("orders.vendors" IS NULL))`,
      cubeInput: {
        measures: ['*'],
        filters: [
          {
            member: 'orders.vendors',
            operator: 'notIn',
            values: ['myntra', 'amazon'],
          },
        ],
        dimensions: [],
      },
      expectedOutput: [
        {
          customer_id: '2',
          order_amount: 25,
          order_date: '2022-02-01T00:00:00.000Z',
          order_id: 3,
          'orders.order_date': undefined,
          'orders.vendors': [],
          product_id: '3',
          vendors: [],
        },
        {
          customer_id: '2',
          order_amount: 75,
          order_date: '2022-03-01T00:00:00.000Z',
          order_id: 4,
          'orders.order_date': undefined,
          'orders.vendors': ['flipkart'],
          product_id: '1',
          vendors: ['flipkart'],
        },
        {
          customer_id: '4',
          order_amount: 45,
          order_date: '2022-04-01T00:00:00.000Z',
          order_id: 6,
          'orders.order_date': undefined,
          'orders.vendors': [],
          product_id: '2',
          vendors: [],
        },
        {
          customer_id: '5',
          order_amount: 85,
          order_date: '2022-05-05T00:00:00.000Z',
          order_id: 9,
          'orders.order_date': undefined,
          'orders.vendors': [],
          product_id: '2',
          vendors: [],
        },
        {
          customer_id: null,
          order_amount: 100,
          order_date: '2024-07-01T00:00:00.000Z',
          order_id: 12,
          'orders.order_date': undefined,
          'orders.vendors': ['flipkart'],
          product_id: '3',
          vendors: ['flipkart'],
        },
        {
          customer_id: '7',
          order_amount: 100,
          order_date: '2024-08-01T00:00:00.000Z',
          order_id: 13,
          'orders.order_date': undefined,
          'orders.vendors': ["swiggy's"],
          product_id: '6',
          vendors: ["swiggy's"],
        },
      ],
    },
  ],
];
