name: Build & Test on PR checks

on:
  pull_request:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - run: npm install
        - run: npx nx run-many --target=build --all --parallel
        - run: npx nx run-many --target=test --all --parallel
        - run: npx nx run-many --target=lint --all --parallel