name: Publish meerkat-library

# on:
#   push:
#     branches:
#       - main

on:
  pull_request:
    branches:
      - main

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.17
          registry-url: https://npm.pkg.github.com/
          scope: '@devrev'
      - run: npm install
      - run: npx nx run-many --target=build --all --parallel
      - run: |
          cd ./dist/meerkat-core
          echo "//npm.pkg.github.com/:_authToken=${{secrets.NPM_PACKAGE_PUBLISH_TOKEN}}" >> .npmrc
          npx semantic-release
      - run: |
          cd ./dist/meerkat-node
          echo "//npm.pkg.github.com/:_authToken=${{secrets.NPM_PACKAGE_PUBLISH_TOKEN}}" >> .npmrc
          npx semantic-release
      - run: |
          cd ./dist/meerkat-browser
          echo "//npm.pkg.github.com/:_authToken=${{secrets.NPM_PACKAGE_PUBLISH_TOKEN}}" >> .npmrc
          npx semantic-release
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PACKAGE_PUBLISH_TOKEN}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
